In [1]:
import sys
import numpy as np
sys.path.append('..')

from NeuralNetwork.led import LED
from particle.generate_particle import ODEParams
from particle.thetamethod import ThetaMethod
from datagen.mitchellschaeffer import MitchellSchaeffer

[[[  4  14  24]]

 [[  5  15  25]]

 [[ -4 -14 -24]]

 [[ -5 -15 -25]]]


In [ ]:
T = 500
dt = 0.1
u0 = [0,0]
def f(v, t): return np.array([-v[1], v[0]])
params = ODEParams(T,dt,u0,f)

params.theta = 0.5
params.tol = 1e-2

TM = ThetaMethod(eqtype='ODE', params=params)

solver = MitchellSchaeffer(TM, 2, 0.1, 0.2, 2, 1, (5,5))
solver.generate_dataset(10,'testdata')

In [ ]:
solver.save_dataset('testdata')

In [ ]:
X = np.load('../../data/dataset/testdata.npy')
np.shape(X)

In [ ]:
NN = LED(latent_dim=4, data_dir='../../data/dataset',saving_dir='../NeuralNetwork/')

input_shape = (5,5,2)
latent_dim = 3

conv = [(4,3)]
dense = (64,128)


NN.build_autoencoder(input_shape=input_shape, conv=conv, dense=dense)

NN.train_autoencoder('testdata.npy')

In [ ]:
NN.build_RNN(input_shape=(5001,4),lstm=[(16,True),(16,True)], dense=(32,64))

In [ ]:
NN.train_RNN('testdata.npy')